### ISSUE TITLE
objects are masked from ‘package:base’:

### ISSUE THREAD

**Issue by Kimland** [DataWookie/CommitmentOfTraders#1]
The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

I don't know if this is a problem since I am a complete starter with R, but I am not seeing results when I run the scripts.  Therefore I am suspecting everything in Read is an issue.

**Comment by datawookie** [comment]
Hi,

I've not looked at this repository for a couple of years. So some parts of it (particularly the data download script) needed to be updated. I've made those changes and I'm in the process of committing the changes.

However the warnings you mention above are just that: warnings. And they refer to things that are happening in libraries that are being loaded by the code in this repository. They do not constitute an "issue".

Regards,
Andrew.

**Comment by Kimland** [comment]
Thanks. I am an eager follower.

**Comment by Kimland** [comment]
Hi Andrew,
I thought I could easily jump into R because I have worked extensively with SAS, but I am finding that I have a lot to learn about the language before I can make sense of the programs you have written to chart COT data.  So I will take some time and start from the basics.
I appreciate getting your attention, but I don't want to misuse it.  I will be back after I familiarize with the program a little more.
Cheers,
Kimland

**Comment by datawookie** [comment]
Good plan. The learning curve with R is a little steep, but it's definitely worth the effort. Let me know if I can help out with specific questions.
